AWSTemplateFormatVersion: 2010-09-09

Description: Sample template that contains common networking components

Parameters:
  VpcCidr:
    Type: String

    Default: 10.10.0.0/16

  PublicSubnetCidr:
    Type: String

    Default: 10.10.1.0/24

Resources:
  #################################################

  ###  Start - Create lab network resources  ###

  #################################################

  Vpc:
    Type: AWS::EC2::VPC

    Properties:
      CidrBlock: !Ref VpcCidr

      EnableDnsSupport: true

      EnableDnsHostnames: true

      InstanceTenancy: default

      Tags:
        - Key: Name

          Value: Lab VPC

  #-----Public subnet resources-----#

  InternetGateway:
    Type: AWS::EC2::InternetGateway

    Properties:
      Tags:
        - Key: Name

          Value: Internet Gateway

  AttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment

    Properties:
      VpcId: !Ref Vpc

      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet

    Properties:
      VpcId: !Ref Vpc

      CidrBlock: !Ref PublicSubnetCidr

      MapPublicIpOnLaunch: true

      AvailabilityZone: !Select
        - 0

        - !GetAZs

      Tags:
        - Key: Name

          Value: Public Subnet

  PublicRouteTable:
    Type: AWS::EC2::RouteTable

    Properties:
      VpcId: !Ref Vpc

  PublicRoute:
    Type: AWS::EC2::Route

    DependsOn: AttachInternetGateway

    Properties:
      RouteTableId: !Ref PublicRouteTable

      DestinationCidrBlock: 0.0.0.0/0

      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation

    Properties:
      SubnetId: !Ref PublicSubnet

      RouteTableId: !Ref PublicRouteTable
############################################

###  End - Create lab network resources  ###

############################################

